In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import plotly.express as px
%matplotlib inline

In [3]:
df=pd.read_csv('cardekho_dataset.csv', index_col=[0])
df.head()

        car_name    brand     model  ...  max_power  seats selling_price
0    Maruti Alto   Maruti      Alto  ...      46.30      5        120000
1  Hyundai Grand  Hyundai     Grand  ...      82.00      5        550000
2    Hyundai i20  Hyundai       i20  ...      80.00      5        215000
3    Maruti Alto   Maruti      Alto  ...      67.10      5        226000
4  Ford Ecosport     Ford  Ecosport  ...      98.59      5        570000

[5 rows x 13 columns]

In [4]:
# data cleaning

df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [5]:
## remove unnecessary columns
df.drop('car_name', axis=1, inplace=True)
df.drop('brand', axis=1, inplace=True)

In [6]:
df.head()

      model  vehicle_age  km_driven  ... max_power seats selling_price
0      Alto            9     120000  ...     46.30     5        120000
1     Grand            5      20000  ...     82.00     5        550000
2       i20           11      60000  ...     80.00     5        215000
3      Alto            9      37000  ...     67.10     5        226000
4  Ecosport            6      30000  ...     98.59     5        570000

[5 rows x 11 columns]

In [7]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [8]:
## getting all different types of features
num_features=[feature for feature in df.columns if df[feature].dtype != 'O']
print('num of numerical features:', len(num_features))
categorical_features=[feature for feature in df.columns if df[feature].dtype == 'O']
print('num of categorical features:', len(categorical_features))
discrete_features=[feature for feature in num_features if len(df[feature].unique())<=25]
print('num of discrete features:', len(discrete_features))
continuous_features=[feature for feature in num_features if feature not in discrete_features]
print('num of continuous features:', len(continuous_features))

num of numerical features: 7
num of categorical features: 4
num of discrete features: 2
num of continuous features: 5

In [9]:
# train test split and model training

from sklearn.model_selection import train_test_split
x=df.drop(['selling_price'], axis=1)
y=df['selling_price']

In [10]:
df.head()

      model  vehicle_age  km_driven  ... max_power seats selling_price
0      Alto            9     120000  ...     46.30     5        120000
1     Grand            5      20000  ...     82.00     5        550000
2       i20           11      60000  ...     80.00     5        215000
3      Alto            9      37000  ...     67.10     5        226000
4  Ecosport            6      30000  ...     98.59     5        570000

[5 rows x 11 columns]

In [11]:
# Label Encoding

len(df['model'].unique())

120

In [12]:
df['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x['model']=le.fit_transform(x['model'])

In [14]:
x.head()

   model  vehicle_age  km_driven seller_type  ... mileage engine  max_power  seats
0      7            9     120000  Individual  ...   19.70    796      46.30      5
1     54            5      20000  Individual  ...   18.90   1197      82.00      5
2    118           11      60000  Individual  ...   17.00   1197      80.00      5
3      7            9      37000  Individual  ...   20.92    998      67.10      5
4     38            6      30000      Dealer  ...   22.77   1498      98.59      5

[5 rows x 10 columns]

In [15]:
len(df['seller_type'].unique()),len(df['fuel_type'].unique()),len(df['transmission_type'].unique())

(3, 5, 2)

In [16]:
## create column transformer with 3 types of transformers
num_features=x.select_dtypes(exclude='object').columns
onehot_columns= ['seller_type', 'fuel_type', 'transmission_type']
label_encoder_columns= ['model']

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop='first')

preprocessor=ColumnTransformer(
    [
        ('OneHotEncoder', oh_transformer, onehot_columns),
        ('StandardScaler', numeric_transformer, num_features)
    ],remainder='passthrough'
)

In [17]:
x=preprocessor.fit_transform(x)

In [18]:
pd.DataFrame(x)

        0    1    2    3   ...        10        11        12        13
0      1.0  0.0  0.0  0.0  ... -0.000276 -1.324259 -1.263352 -0.403022
1      1.0  0.0  0.0  0.0  ... -0.192071 -0.554718 -0.432571 -0.403022
2      1.0  0.0  0.0  0.0  ... -0.647583 -0.554718 -0.479113 -0.403022
3      1.0  0.0  0.0  0.0  ...  0.292211 -0.936610 -0.779312 -0.403022
4      0.0  0.0  1.0  0.0  ...  0.735736  0.022918 -0.046502 -0.403022
...    ...  ...  ...  ...  ...       ...       ...       ...       ...
15406  0.0  0.0  0.0  0.0  ...  0.026096 -0.767733 -0.757204 -0.403022
15407  0.0  0.0  0.0  0.0  ... -0.527711 -0.216964 -0.220803  2.073444
15408  0.0  0.0  1.0  0.0  ...  0.344954  0.022918  0.068225 -0.403022
15409  0.0  0.0  1.0  0.0  ... -0.887326  1.329794  0.917158  2.073444
15410  0.0  0.0  0.0  0.0  ... -0.407839  0.020999  0.395884 -0.403022

[15411 rows x 14 columns]

In [19]:
## seprate dataset into train test split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape, x_test.shape

((12328, 14), (3083, 14))

In [20]:
x_train

array([[ 0.        ,  0.        ,  1.        , ...,  1.75390551,
         2.66249771, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55087963,
        -0.38602844, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  0.89033072,
         3.27453006, -0.40302241],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.9366097 ,
        -0.78070786, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43582879, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06194201, -0.40302241]], shape=(12328, 14))

In [21]:
# model training and model selection

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [22]:
## create a function to evaluate model
def evaluate_model(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)  
    return mae, rmse, r2

In [23]:
## beggining model training
models={
    "Linear regression":LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
    "K-Neighbors regression":KNeighborsRegressor(),
    "Decision Tree":DecisionTreeRegressor(),
    "Random Forest regressor":RandomForestRegressor(),
    "Adaboost Regressor":AdaBoostRegressor(),
    "Gredientboost Regressor":GradientBoostingRegressor(),
    "XGB Regressor":XGBRegressor()
}

for i in range(len(list(models))):
    model= list(models.values())[i]
    model.fit(x_train,y_train)

    # make prediction
    y_train_pred= model.predict(x_train)
    y_test_pred= model.predict(x_test)

    # evaluate train and test model
    model_train_mae , model_train_rmse, model_train_r2= evaluate_model(y_train,y_train_pred)
    model_test_mae , model_test_rmse, model_test_r2= evaluate_model(y_test,y_test_pred)

    print(list(models.keys())[i])

    print("Model performance for training set")

    print("- Root mean squared error: {:.4f}".format(model_train_rmse))
    print("- Mean absolute error: {:.4f}".format(model_train_mae))
    print("- R2 score: {:.4f}".format(model_train_r2))

    print('--------------------------------')

    print("Model performance for test set")

    print("- Root mean squared error: {:.4f}".format(model_test_rmse))
    print("- Mean absolute error: {:.4f}".format(model_test_mae))
    print("- R2 score: {:.4f}".format(model_test_r2))

    
    print('='*35)
    print('\n')

Linear regression
Model performance for training set
- Root mean squared error: 553855.6665
- Mean absolute error: 268101.6071
- R2 score: 0.6218
--------------------------------
Model performance for test set
- Root mean squared error: 502543.5930
- Mean absolute error: 279618.5794
- R2 score: 0.6645
===================================


Lasso
Model performance for training set
- Root mean squared error: 553855.6710
- Mean absolute error: 268099.2226
- R2 score: 0.6218
--------------------------------
Model performance for test set
- Root mean squared error: 502542.6696
- Mean absolute error: 279614.7461
- R2 score: 0.6645
===================================


Ridge
Model performance for training set
- Root mean squared error: 553856.3160
- Mean absolute error: 268059.8015
- R2 score: 0.6218
--------------------------------
Model performance for test set
- Root mean squared error: 502533.8230
- Mean absolute error: 279557.2169
- R2 score: 0.6645
===================================


K-Neighbors regression
Model performance for training set
- Root mean squared error: 325886.0010
- Mean absolute error: 91431.1324
- R2 score: 0.8691
--------------------------------
Model performance for test set
- Root mean squared error: 253071.9428
- Mean absolute error: 112672.8917
- R2 score: 0.9149
===================================


Decision Tree
Model performance for training set
- Root mean squared error: 20797.2352
- Mean absolute error: 5164.8199
- R2 score: 0.9995
--------------------------------
Model performance for test set
- Root mean squared error: 311180.9716
- Mean absolute error: 124513.3447
- R2 score: 0.8714
===================================


Random Forest regressor
Model performance for training set
- Root mean squared error: 132289.8368
- Mean absolute error: 40112.4958
- R2 score: 0.9784
--------------------------------
Model performance for test set
- Root mean squared error: 226461.6386
- Mean absolute error: 101377.9150
- R2 score: 0.9319
===================================


Adaboost Regressor
Model performance for training set
- Root mean squared error: 439115.0340
- Mean absolute error: 313797.2748
- R2 score: 0.7623
--------------------------------
Model performance for test set
- Root mean squared error: 467913.3988
- Mean absolute error: 332191.2021
- R2 score: 0.7092
===================================


Gredientboost Regressor
Model performance for training set
- Root mean squared error: 204944.5104
- Mean absolute error: 111709.5558
- R2 score: 0.9482
--------------------------------
Model performance for test set
- Root mean squared error: 260036.7807
- Mean absolute error: 127010.3775
- R2 score: 0.9102
===================================


XGB Regressor
Model performance for training set
- Root mean squared error: 85441.7947
- Mean absolute error: 61009.3203
- R2 score: 0.9910
--------------------------------
Model performance for test set
- Root mean squared error: 246853.8159
- Mean absolute error: 99048.5078
- R2 score: 0.9191
===================================

In [24]:
## initialize few parameter for hyperparameter tuning
knn_params= {"n_neighbors":[2,3,10,20,40,50]}
rf_params={"max_depth":[5,8,15,None,10],
           "max_features":[5,7,'auto',8],
           "min_samples_split":[2,8,15,20],
           "n_estimators":[100,200,500,1000]
}
ada_params= {"n_estimators":[50,60,70,80],
             "loss":['linear', 'square', 'exponential']
             }

gradient_params={"loss":['squared_error','huber','absolute_error'],
                "criterion":['friedman_mse','squared_error','mse'], 
                "min_samples_split":[2,8,15,20],
                "n_estimators":[100,200,500,1000], 
                "max_depth":[5,8,15,None,10],
                "learning_rate":[0.1,0.01,0.02,0.03]
                 }

xgboost_params={"learning_rate":[0.1,0.01],
                "max_depth":[5,8,12,20,30],
                "n_estimators":[100,200,300],
                "colsample_bytree":[0.5,0.8,1,0.3,0.4]}

In [25]:
## models list of hyperparameter tuning
randomcv_models=[
    ('KNN', KNeighborsRegressor(), knn_params),
    ("RF", RandomForestRegressor(), rf_params),
    ("Adaboost", AdaBoostRegressor(), ada_params),
    ("Gadient", GradientBoostingRegressor(), gradient_params),
    ("XGBRegressor",XGBRegressor(), xgboost_params)
]
randomcv_models

[('KNN', KNeighborsRegressor(), {'n_neighbors': [2, 3, 10, 20, 40, 50]}),
 ('RF',
  RandomForestRegressor(),
  {'max_depth': [5, 8, 15, None, 10],
   'max_features': [5, 7, 'auto', 8],
   'min_samples_split': [2, 8, 15, 20],
   'n_estimators': [100, 200, 500, 1000]}),
 ('Adaboost',
  AdaBoostRegressor(),
  {'n_estimators': [50, 60, 70, 80],
   'loss': ['linear', 'square', 'exponential']}),
 ('Gadient',
  GradientBoostingRegressor(),
  {'loss': ['squared_error', 'huber', 'absolute_error'],
   'criterion': ['friedman_mse', 'squared_error', 'mse'],
   'min_samples_split': [2, 8, 15, 20],
   'n_estimators': [100, 200, 500, 1000],
   'max_depth': [5, 8, 15, None, 10],
   'learning_rate': [0.1, 0.01, 0.02, 0.03]}),
 ('XGBRegressor',
  XGBRegressor(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, device=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric=None, feature_types=None,
               feature_weights=None, gamma=None, grow_policy=None,
               importance_type=None, interaction_constraints=None,
               learning_rate=None, max_bin=None, max_cat_threshold=None,
               max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
               max_leaves=None, min_child_weight=None, missing=nan,
               monotone_constraints=None, multi_strategy=None, n_estimators=None,
               n_jobs=None, num_parallel_tree=None, ...),
  {'learning_rate': [0.1, 0.01],
   'max_depth': [5, 8, 12, 20, 30],
   'n_estimators': [100, 200, 300],
   'colsample_bytree': [0.5, 0.8, 1, 0.3, 0.4]})]

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

model_param= {}
for name, model, params in randomcv_models:
    random= RandomizedSearchCV(estimator=model,
                               param_distributions=params,
                               n_iter=100,
                               cv=3,
                               verbose=2,
                               n_jobs=-1)
    random.fit(x_train, y_train)
    model_param[name]= random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} ---------------------------")
    print(model_param[model_name])

In [27]:
models = {
    "Random Forest": RandomForestRegressor(n_estimators=100,min_samples_split=2,max_features=8,max_depth=10,n_jobs=-1),
    "K-Neighbors Regressor":KNeighborsRegressor(n_neighbors=10,n_jobs=-1),
    "Adaboost":AdaBoostRegressor(n_estimators=50, loss='linear'),
    "Gadientboostregressor": GradientBoostingRegressor(loss='squared_error',criterion='friedman_mse',min_samples_split=2, n_estimators=200,max_depth=5,learning_rate=0.1),
    "Xgboost Regressor": XGBRegressor(learning_rate=0.1,max_depth=8,n_estimators=200,colsample_bytree=0.8,n_jobs=-1)
}

for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(x_train, y_train)

    # make prediction
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)

    # evaluate train and test model
    model_train_mae , model_train_rmse, model_train_r2= evaluate_model(y_train,y_train_pred)
    model_test_mae , model_test_rmse, model_test_r2= evaluate_model(y_test,y_test_pred)

    print(list(models.keys())[i])

    print("Model performance for training set")

    print("- Root mean squared error: {:.4f}".format(model_train_rmse))
    print("- Mean absolute error: {:.4f}".format(model_train_mae))
    print("- R2 score: {:.4f}".format(model_train_r2))

    print('--------------------------------')

    print("Model performance for test set")

    print("- Root mean squared error: {:.4f}".format(model_test_rmse))
    print("- Mean absolute error: {:.4f}".format(model_test_mae))
    print("- R2 score: {:.4f}".format(model_test_r2))

    
    print('='*35)
    print('\n')

Random Forest
Model performance for training set
- Root mean squared error: 174247.6466
- Mean absolute error: 84262.5283
- R2 score: 0.9626
--------------------------------
Model performance for test set
- Root mean squared error: 223475.3449
- Mean absolute error: 105862.0121
- R2 score: 0.9337
===================================


K-Neighbors Regressor
Model performance for training set
- Root mean squared error: 363465.8791
- Mean absolute error: 103490.1525
- R2 score: 0.8371
--------------------------------
Model performance for test set
- Root mean squared error: 263849.0158
- Mean absolute error: 117479.0221
- R2 score: 0.9075
===================================


Adaboost
Model performance for training set
- Root mean squared error: 459502.7154
- Mean absolute error: 355376.9485
- R2 score: 0.7397
--------------------------------
Model performance for test set
- Root mean squared error: 496706.1302
- Mean absolute error: 374226.3702
- R2 score: 0.6723
===================================


Gadientboostregressor
Model performance for training set
- Root mean squared error: 110967.8599
- Mean absolute error: 74260.8858
- R2 score: 0.9848
--------------------------------
Model performance for test set
- Root mean squared error: 217137.9860
- Mean absolute error: 98585.0389
- R2 score: 0.9374
===================================


Xgboost Regressor
Model performance for training set
- Root mean squared error: 75197.1438
- Mean absolute error: 54396.7070
- R2 score: 0.9930
--------------------------------
Model performance for test set
- Root mean squared error: 289152.2833
- Mean absolute error: 102021.3750
- R2 score: 0.8889
===================================