In [21]:
## two tech:  1)up sampling   2)down sampling

import numpy as np
import pandas as pd

In [22]:
## set the  random seed for reproductivity
np.random.seed(123)

## create a dataframe with the classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples*class_0_ratio)
n_class_1 = n_samples-n_class_0

In [23]:
n_class_0,n_class_1

(900, 100)

In [24]:
## create dataframe with imbalanced dataset
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1 ,size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1 ,size=n_class_0),
    'target':[0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1 ,size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1 ,size=n_class_1),
    'target':[1] * n_class_1
})

In [25]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [26]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [27]:
## upsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [30]:
!pip install scikit-learn
from sklearn.utils import resample

Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (2.3.5)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 33.6 MB/s  0:00:01m0:00:0100:01
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [33]:
df_minority_majority=resample(df_minority,replace=True,
         n_samples=len(df_majority),
         random_state=42
         )

In [34]:
df_minority_majority.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [36]:
df_upsampled=pd.concat([df_majority,df_minority_majority])

In [38]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [39]:
# down sampling

In [41]:
## create dataframe with imbalanced dataset
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1 ,size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1 ,size=n_class_0),
    'target':[0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1 ,size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1 ,size=n_class_1),
    'target':[1] * n_class_1
})

df=pd.concat([class_0,class_1]).reset_index(drop=True)

# check the class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [42]:
## downsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [44]:
df_majority_downsample=resample(df_majority,replace=False,
         n_samples=len(df_minority),
         random_state=42
         )

In [45]:
df_majority_downsample.shape

(100, 3)

In [46]:
df_downsampled=pd.concat([df_minority,df_majority_downsample])

In [47]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64